name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
  
    # - name: hello
    #   run:
    #     echo "Hello"

    - name: Grant execute permission for gradlew  # build 권한 추가
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper  # build
      run: ./gradlew build

    # - name: Zip files  # file 이름 설정, 압축
    #   run: |
    #     # SHA="${{ github.sha }}"
    #     # FILENAME=$(git rev-parse --short HEAD)_$(date "+%m-%d-%H-%M").tar.gz
    #     # tar -zcvf ./$FILENAME ./build/libs/penguin-0.0.1-SNAPSHOT.war

    - name: Zip files  # file 이름 설정, 압축
      run: |
        tar -zcvf ./test.tar.gz ./build/libs/penguin-0.0.1-SNAPSHOT.war

    - name: Google auth  # GCP 권한 설정
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Use gcloud CLI
      run: gcloud storage cp ./test.tar.gz gs://${{ secrets.BUCKET }}
